name: Zipline CI

on:  # TMP: change workflow to run on push to master
  push:
    branches:
      - gh-actions-ci

jobs:
  build-and-test:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: true
      matrix:
        python: [2.7, 3.5]
        pandas: ['old', 'new']
        exclude:
          - python: 2.7
            pandas: 'new'
        include:
          - pandas: 'old'
            NUMPY_VERSION: 1.11.3
            PANDAS_VERSION: 0.18.1
            SCIPY_VERSION: 0.17.1
          - pandas: 'new'
            NUMPY_VERSION: 1.14.1
            PANDAS_VERSION: 0.22.0
            SCIPY_VERSION: 1.0.0
            PANDAS_DATAREADER_VERSION: 0.4.0
            DASK_VERSION: 0.17.1


    name: py ${{ matrix.python }}/${{ matrix.pandas }} pandas
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Cache pip files
        uses: actions/cache@v1
        with:
          path: ~/.cache/.pip
          key: ${{ matrix.python }}/${{ matrix.pandas }}
      - name: Install dependencies
        env:
          ANACONDA_TOKEN: ${{ secrets.AnacondaToken }}
          CONDA_ROOT_PYTHON_VERSION: "2.7"
          NUMPY_VERSION: ${{ matrix.NUMPY_VERSION }}
          PANDAS_VERSION: ${{ matrix.PANDAS_VERSION }}
          SCIPY_VERSION: ${{ matrix.SCIPY_VERSION }}
        run: |
          if [[ matrix.PANDAS_DATAREADER_VERSION ]]; then export PANDAS_DATAREADER_VERSION=${{ matrix.PANDAS_DATAREADER_VERSION }}; fi
          if [[ matrix.DASK_VERSION ]]; then export DASK_VERSION=${{ matrix.DASK_VERSION }}; fi
          source ./ci/travis/install_miniconda.sh
